### ISSUE TITLE
Occupancy sensor instead of contact-sensor?

### ISSUE THREAD

**Issue by mensa84** [lzilioli/nokia-sleep-homebridge#2]
Hello,

I am not sure, if just switching a contact sensor every time you get in or out of bed will work reliable.
Do you know if the Withings Sleep mat ha included an "occupancy" sensor? Maybe it's better to use that sensor directly?

**Comment by lzilioli** [comment]
@mensa84 the withings has no direct homekit integration, which is why I needed this bridge to begin with.

I've switched over to PushCut's automation server and thus am archiving this repo.

Feel free to fork and modify this code as you see fit. Happy hacking!
